# admin/config.yml
backend:
  name: git-gateway
  branch: dev # Specify the branch you want to work with

media_folder: "assets/img" # Folder where images are stored
public_folder: "/img" # URL to access images

collections:
  - name: "employee-newsletter"
    label: "Employee Newsletters"
    folder: "_posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Publish Date", name: "date", widget: "datetime" }